### ISSUE TITLE
Unable to upload source map

### ISSUE THREAD

**Issue by becaLG** [bugsnag/bugsnag-vue#10]
hi there.
   I have some problems, can you help me?
![1](https://user-images.githubusercontent.com/6837666/42812788-60412c40-89f1-11e8-93db-70c86616c227.png)
![2](https://user-images.githubusercontent.com/6837666/42812797-63f2ce52-89f1-11e8-84ec-23123e21b959.png)
![3](https://user-images.githubusercontent.com/6837666/42812806-66ff2514-89f1-11e8-9296-f1a603832162.png)

**Comment by bengourley** [comment]
Hi @becaLG – this doesn't look like a bug, it looks like you are trying to supply a glob argument to `bugsnag-sourcemaps` which wants a single file path.

Since this isn't an issue with bugsnag-vue, I'm going to close this, but if you still need help please email support@bugsnag.com.

**Comment by becaLG** [comment]
hi there.
I uploaded the file but it is still incorrect.I don't know where it is not
correct.
Please help me, thank you.

Ben Gourley <notifications@github.com> 于2018年7月18日周三 下午4:51写道：
