### ISSUE TITLE
about `window.Vue`

### ISSUE THREAD

**Issue by Hilbertangers** [bugsnag/bugsnag-vue#11]
Read your src, you use``` window.Vue ``` as a basis for deciding whether to use vue.js，
But...my project usual not mount Vue on window.
I hope you can write this into ReadMe as tips.

**Comment by bengourley** [comment]
Hi @Hilbertangers, our Vue.js documentation lives here:
https://docs.bugsnag.com/platforms/browsers/vue/

With regard to your question, `Vue` should be passed in, but if it isn't we check to see if it exists on the window as a fallback. Hope this helps!
