### ISSUE TITLE
Recommended use for handled errors?

### ISSUE THREAD

**Issue by kevinjcoleman** [bugsnag/bugsnag-vue#2]
I'm currently doing the following in my main.js in order to use `bugsnagClient.notify` in other files, like my index.js's router. I was wondering how you would recommend using it? Putting something about this in the readme would be helpful because I'm sure most people don't want to initialize the client in multiple places.
```
import Vue from 'vue'
import bugsnag from 'bugsnag-js'
import bugsnagVue from 'bugsnag-vue'

if (process.env.NODE_ENV === 'production') {
  const bugsnagClient = bugsnag('api_key')
  bugsnagClient.use(bugsnagVue(Vue))
  window.bugsnagClient = bugsnagClient
}
```

**Comment by bengourley** [comment]
Hey Kevin, thanks for posting this. It's definitely best to only initialize one client so we'll take a look at making the docs clearer for people using a bundler. I personally wouldn't attach it to the `window` object without good reason, I'd factor it out into a different module and require that, e.g.

```js
/* lib/bugsnag.js or something… */
import bugsnag from 'bugsnag-js'
const bugsnagClient = bugsnag('api_key')
export bugsnagClient
```

```js
/* your Vue app init */
import bugsnagClient from 'lib/bugsnag'
import bugsnagVue from 'bugsnag-vue'

bugsnagClient.use(bugsnagVue(Vue))
```


```js
/* some other part of your app */
import bugsnagClient from 'lib/bugsnag'
try {
  // something risky
} catch (e) {
  bugsnagClient.notify(e)
}
```

Additionally, if you used the [`releaseStage`](https://docs.bugsnag.com/platforms/browsers/js/configuration-options/#releasestage) and [`notifyReleaseStages`](https://docs.bugsnag.com/platforms/browsers/js/configuration-options/#notifyreleasestages) configurations options, you could avoid some of the conditional logic you have around init'ing bugsnag, and also then avoid checks to see if it exists before using it elsewhere.

**Comment by kevinjcoleman** [comment]
@bengourley awesome, thanks for the advice and the tips about releaseStage and notifiyReleaseStages, that definitely cleans up a lot of the logic.
