### ISSUE TITLE
ReferenceError: bugsnagClient is not defined - how to access the bugsnagClient

### ISSUE THREAD

**Issue by marijnhurkens** [bugsnag/bugsnag-vue#6]
Hi,

I have a problem with reporting a handled error. I initialize the Bugsnag in the following way:

```js
import bugsnag from 'bugsnag-js'
const bugsnagClient = bugsnag('key-here')
import Vue from 'vue'
import bugsnagVue from'bugsnag-vue'
bugsnagClient.use(bugsnagVue(Vue))
```

This seems to work fine. Now I want to report a handled error in a Vuex store:

```js
    async fetchAccountValue({commit}) {
        try {
            const {data} = await axios.get('/api/v1/user/account-value')

            commit(types.FETCH_ACCOUNT_VALUE_SUCCESS, {result: data.data})
        } catch (error) {
            commit(types.FETCH_ACCOUNT_VALUE_FAILURE)

            bugsnagClient.notify(error)
        }
    }
```

If the request fails I get the following console error: `ReferenceError: bugsnagClient is not defined`

How can I access the `bugsnagClient` in another js file. Normally I would import it but it would require the api key again I assume? I could also make the object global by adding it to the window object but I'd rather not.

**Comment by marijnhurkens** [comment]
I think I found the answer here: https://github.com/bugsnag/bugsnag-vue/issues/2

**Comment by bengourley** [comment]
Hi @marijnhurkens, typically lots of people assign it to `window` but if you don't want to do that, you can stick the initialization in its own file and include that everywhere:

_bugsnag.js_
```js
import bugsnag from 'bugsnag-js'
const bugsnagClient = bugsnag('key-here')
export default bugsnagClient
```

then in your other files you can do…

_vue initialization_
```js
import bugsnagClient from './bugsnag'
import bugsnagVue from 'bugsnag-vue'
import Vue from 'vue'
bugsnagClient.use(bugsnagVue(Vue))
```

_vuex stores_
```js
import bugsnagClient from './bugsnag'

// ...

    async fetchAccountValue({commit}) {
        try {
            const {data} = await axios.get('/api/v1/user/account-value')

            commit(types.FETCH_ACCOUNT_VALUE_SUCCESS, {result: data.data})
        } catch (error) {
            commit(types.FETCH_ACCOUNT_VALUE_FAILURE)

            bugsnagClient.notify(error)
        }
    }
```
