### ISSUE TITLE
Filtering out confidential props value

### ISSUE THREAD

**Issue by vinibrsl** [bugsnag/bugsnag-vue#9]
### Expected behavior
`bugsnag-vue` should provide a way to filter the Vue props values.
 
### Observed behavior
There's no option to filter component props or documentation provided on [Vue integration guide](https://docs.bugsnag.com/platforms/browsers/vue/).

Some props such as credit card information are confidential and should not appear on Bugsnag Dashboard.

**Comment by bengourley** [comment]
Hi @vnbrs, thanks for getting in touch!

We currently don't provide the "filter" configuration on bugsnag-js like we do on other platforms such as ruby. I think we probably should so I'll create an internal backlog ticket to do this.

In the mean time, you can implement a custom `beforeSend` function to filter out parts of the payload, for example:

```js
var FILTER_PROPS = [ 'password' /* ...and more */ ]
bugsnag({
  apiKey: 'API_KEY',
  beforeSend: function (report) {
    if (report.metaData.vue && report.metaData.vue.props) {
      for (var key in report.metaData.vue.props) {
        if (FILTER_PROPS.indexOf(key) !== -1) {
          report.metaData.vue.props[key] = '[filtered]'
        }
      }
    }
  }
})
```

Hope this helps. Let us know if you have any more questions around this!
Cheers

**Comment by vinibrsl** [comment]
Hi!

The https://github.com/bugsnag/bugsnag-ruby implements this, and so does other Bugsnag libraries. This is a really important feature! Are there any updates about it on the Vue implementation of it?

**Comment by bengourley** [comment]
We just released our "universal" JS notifier [@bugsnag/js](https://github.com/bugsnag/bugsnag-js) which implements this feature. Docs are [here](https://docs.bugsnag.com/platforms/javascript/configuration-options/#filters).

Closing this off now 🚀
